from model.model import Package


def all_packages():
    return [
        Package(
            0,
            'boto3',
            'None',
            'None',
            True,
            'boto/boto3',
            []
        ),
        Package(
            0,
            'urllib3',
            'None',
            'None',
            True,
            'urllib3/urllib3',
            []
        ),
        Package(
            0,
            'botocore',
            'None',
            'None',
            True,
            'boto/botocore',
            []
        ),
        Package(
            0,
            'setuptools',
            'None',
            'None',
            True,
            'pypa/setuptools',
            []
        ),
        Package(
            0,
            'idna',
            'None',
            'None',
            True,
            'kjd/idna',
            []
        ),
        Package(
            0,
            's3transfer',
            'None',
            'None',
            True,
            'boto/s3transfer',
            []
        ),
        Package(
            0,
            'requests',
            'None',
            'None',
            True,
            'psf/requests',
            []
        ),
        Package(
            0,
            'six',
            'None',
            'None',
            True,
            'benjaminp/six',
            []
        ),
        Package(
            0,
            'typing',
            'None',
            'None',
            True,
            'python/typing',
            []
        ),
        Package(
            0,
            'python-certifi',
            'None',
            'None',
            True,
            'certifi/python-certifi',
            []
        ),
        Package(
            0,
            'dateutil',
            'None',
            'None',
            True,
            'dateutil/dateutil',
            []
        ),
        Package(
            0,
            'aws-cli',
            'None',
            'None',
            True,
            'aws/aws-cli',
            []
        ),
        Package(
            0,
            'pyyaml',
            'None',
            'None',
            True,
            'yaml/pyyaml',
            []
        ),
        Package(
            0,
            'charset_normalizer',
            'None',
            'None',
            True,
            'Ousret/charset_normalizer',
            []
        ),
        Package(
            0,
            'wheel',
            'None',
            'None',
            True,
            'pypa/wheel',
            []
        ),
        Package(
            0,
            'click',
            'None',
            'None',
            True,
            'pallets/click',
            []
        ),
        Package(
            0,
            'numpy',
            'None',
            'None',
            True,
            'numpy/numpy',
            []
        ),
        Package(
            0,
            'attrs',
            'None',
            'None',
            True,
            'python-attrs/attrs',
            []
        ),
        Package(
            0,
            'cryptography',
            'None',
            'None',
            True,
            'pyca/cryptography',
            []
        ),
        Package(
            0,
            'packaging',
            'None',
            'None',
            True,
            'pypa/packaging',
            []
        )
    ]